# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

# Artifacts Configuration for wallet-attribute-attestation
# Defines what to build and where to publish

artifacts:
  - name: wallet-attribute-attestation
    project-type: maven
    working-directory: .
    build-type: application
    config:
      java-version: 21

containers:
  - name: wallet-attribute-attestation
    from: [wallet-attribute-attestation]
    container-file: Containerfile
    context: .
    platforms: linux/amd64,linux/arm64
    registry: ghcr.io

publishers:
  - type: github-packages
    artifacts: [wallet-attribute-attestation]
