# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

---
name: OpenSSF Scorecard Analysis
on:
  schedule:
    # Saturdays at 02:25 UTC
    - cron: "25 2 * * 6"
    # Wednesdays at 02:25 UTC
    - cron: "25 2 * * 3"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scorecard-analysis:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: diggsweden/reusable-ci/.github/workflows/security-openssf-scorecard.yml@v2
    with:
      publish-results: true
